### ISSUE TITLE
The pre-trained hifigan model

### ISSUE THREAD

**Issue by XierHacker** [p0p4k/pflowtts_pytorch#10]
Thank you very much for your work. 
I have a question that your inference code uses a pre-trained hifigan model. So where can I download this hifigan model?

**Comment by p0p4k** [comment]
Hi, the links are in this file https://github.com/p0p4k/pflowtts_pytorch/blob/master/pflow/cli.py

**Comment by XierHacker** [comment]
> Hi, the links are in this file https://github.com/p0p4k/pflowtts_pytorch/blob/master/pflow/cli.py

thanks! It's works now!

**Comment by p0p4k** [comment]
How are your samples quality?
