### ISSUE TITLE
How to perform fine-tuning?

### ISSUE THREAD

**Issue by HobisPL** [p0p4k/pflowtts_pytorch#17]
I've trained a model and would like to use it as a base for training another speaker, where should I specify the path to the pre-trained model?

**Comment by p0p4k** [comment]
See train.yaml checkpoint path, under configs.

**Comment by HobisPL** [comment]
> See train.yaml checkpoint path, under configs.

Do you mean the 'ckpt_path:' ? 
But that is for resuming training; epochs, etc., are from the previous training.

**Comment by p0p4k** [comment]
Yes you can resume with a new dataset and set epochs to 0 using on load checkpoint, see pytorch lightning details for more info.

**Comment by HobisPL** [comment]
Ok, thanks for the reply

**Comment by p0p4k** [comment]
Hi, 
in train.py 
after Instantiating model ... add this 
```
    if cfg.get("transfer_ckpt_path"):
        model.load_state_dict(torch.load(cfg.get("transfer_ckpt_path"), map_location="cpu")['state_dict'])
        log.info(f"Loaded model from {cfg.get('transfer_ckpt_path')}")
```
In train.yaml,
add a new flag "transfer_ckpt_path" (like cpkt_path).
This flag will just load the state dict (weights) and ignore everything else from the pretrained model. Try and let me know if it works.

**Comment by p0p4k** [comment]
if you use pytorch lightning , load_from_checkpoint , it loads everything (hparams, etc) and then it is basically almost like resuming training, instead of transfer. So i think using pytorch state dict load is better.

**Comment by Oleksandr2505** [comment]
> if you use pytorch lightning , load_from_checkpoint , it loads everything (hparams, etc) and then it is basically almost like resuming training, instead of transfer. So i think using pytorch state dict load is better.

Hi, It is working , Thank you!
