### ISSUE TITLE
Prior or encoder Loss

### ISSUE THREAD

**Issue by epii2zero** [p0p4k/pflowtts_pytorch#18]
Thank you for nice work!

I have a question about encoder loss
In paper they used MSE for encoder loss (section 3.1)
![image](https://github.com/p0p4k/pflowtts_pytorch/assets/53642319/4e988009-3fe5-42bf-a0fc-c8dfc68a5908)

but in this implementation, use different loss
https://github.com/p0p4k/pflowtts_pytorch/blob/297166f518263b2822f52918f86f7d27fa72fe8b/pflow/models/pflow_tts.py#L179C9-L180C74

I think this loss came from Matcha-TTS codes
Is this intentional?

Thank you!

**Comment by p0p4k** [comment]
Essentially it is the same loss, scaled. (at a constant variance of 1, gaussian nle becomes mse)

**Comment by epii2zero** [comment]
Oh I see, thank you for reply
