### ISSUE TITLE
Noise in e2e branch

### ISSUE THREAD

**Issue by Tera2Space** [p0p4k/pflowtts_pytorch#19]
I'm trying to train e2e branch but the result is only noise in the audio, am I doing something wrong or is this version not ready yet? Basically hifigan out is just -1 tensor, so maybe i made mistake somewhere.

**Comment by p0p4k** [comment]
Not completely ready yet. I feel like that training will not work in single stage. It has to be done in 2 stages like naturalspeech2. Train a model to get latents and then use those latents as target for pflow. Thats why I made an encodec based branch which has pretrained latents.

**Comment by Tera2Space** [comment]
Thanks for response, got it :)
