### ISSUE TITLE
Unused model

### ISSUE THREAD

**Issue by Tera2Space** [p0p4k/pflowtts_pytorch#23]
In speech_prompt_encoder we define [speech_prompt_encoder](https://github.com/p0p4k/pflowtts_pytorch/blob/master/pflow/models/components/speech_prompt_encoder.py#L512) but it's usage is [commented](https://github.com/p0p4k/pflowtts_pytorch/blob/master/pflow/models/components/speech_prompt_encoder.py#L607) 
So model is unused or used in different place?

**Comment by p0p4k** [comment]
There are two ways to project the speech prompt to desired channels. I am using one and commenting the other. Either can be used.

**Comment by Tera2Space** [comment]
I mean that the model creation is not commented but then model is not called anywhere, in this case it just takes up space.

**Comment by p0p4k** [comment]
I see, good catch. Can be commented out if not used.
