### ISSUE TITLE
How ready is multispeaker training?

### ISSUE THREAD

**Issue by igbeller** [p0p4k/pflowtts_pytorch#3]
found this TODO
https://github.com/p0p4k/pflowtts_pytorch/blob/b00f7b45ad777c21fa42b77cd36df87e2ceeb9ef/pflow/data/text_mel_datamodule.py#L169

would like to try multispeaker training, it this good to have fixed for that or could i already give it a go?

**Comment by p0p4k** [comment]
The only small issue I need to fix is samples less than 3 seconds must be either discarded or use another sample as a prompt. I'll do it today or tomorrow.
