### ISSUE TITLE
2nd-order Heun's method for ODE sampling

### ISSUE THREAD

**Issue by kunibald413** [p0p4k/pflowtts_pytorch#36]
as mentioned here
https://openreview.net/forum?id=zNA7u7wtIN&noteId=aiIagkNqgq

https://openreview.net/attachment?id=Ymg8GZvGds&name=pdf

you have a take on this and would it be easy to implement and try?

**Comment by p0p4k** [comment]
Will try it, if you have any resources for it lmk.

**Comment by igbeller** [comment]
I have to say that i have close to no experience with this kind of math.

maybe this has some inspiration (searched heun's method on github)

https://github.com/matplotlib/matplotlib/blob/9618fc6322745834dd098cadecf8e05a0917d498/lib/matplotlib/streamplot.py#L514C17-L514C19

https://github.com/openai/shap-e/blob/50131012ee11c9d2617f3886c10f000d3c7a3b43/shap_e/diffusion/k_diffusion.py#L273
