### ISSUE TITLE
some other question about the paper

### ISSUE THREAD

**Issue by JohnHerry** [p0p4k/pflowtts_pytorch#46]
@p0p4k  
Hi,  p0p4k,  I am learning the paper but because of my bad mathmetical basis,  I do want to make it clear that: what is the flow means at all?  and what is the vector field means?  is a flow means a state of data distribution? can you give me a more concerate discription to help me understand those concepts?  Thank you very much!

**Comment by ummjevel** [comment]
hi, @JohnHerry.

I hope this message finds you well. 
I've been looking into your inquiry and would like to offer some suggestions that might be helpful.

For a comprehensive understanding, the classic approach of reading the cited papers in the original research is always valuable. However, if you're seeking a quicker method to grasp the concepts, I'd like to recommend the following resources:

1. A blog post about flow-based generative models: https://lilianweng.github.io/posts/2018-10-13-flow-models/
2. A YouTube video offering a concise overview from flow to flow matching: https://www.youtube.com/watch?v=DDq_pIfHqLs&t=193s

Wishing you all the best in your studies. Have a lovely day!
Kind regards,
mj

**Comment by JohnHerry** [comment]
> hi, @JohnHerry.
> 
> I hope this message finds you well. I've been looking into your inquiry and would like to offer some suggestions that might be helpful.
> 
> For a comprehensive understanding, the classic approach of reading the cited papers in the original research is always valuable. However, if you're seeking a quicker method to grasp the concepts, I'd like to recommend the following resources:
> 
> 1. A blog post about flow-based generative models: https://lilianweng.github.io/posts/2018-10-13-flow-models/
> 2. A YouTube video offering a concise overview from flow to flow matching: https://www.youtube.com/watch?v=DDq_pIfHqLs&t=193s
> 
> Wishing you all the best in your studies. Have a lovely day! Kind regards, mj

Thanks for you kindly help,  ummjevel, Thank you very much!
