### ISSUE TITLE
pflow/data/text_mel_datamodule.py __getitem__

### ISSUE THREAD

**Issue by zidsi** [p0p4k/pflowtts_pytorch#5]
```python
if len(datapoint["wav"]) < 66150:
```
datapoint['wav'] is [[...]]  and len is allways 1. So datapoint["wav"][0] might be what you are looking for.

And for multispeaker datasets, random from same speaker might be better alternative.

**Comment by zidsi** [comment]
Still struggling with configs (hydra) to start training.

**Comment by p0p4k** [comment]
Let me know where you have any bugs/errors so I can help you get the model running.

**Comment by zidsi** [comment]
Tnx. Getting there. Nohop redirected log didn't show any progress, but tensorboard is looking good. I'll have to try E2E branch or train HiFiGAN for custom dataset thogh before any comparisment to VITS2.

**Comment by zidsi** [comment]
Single speaker training is progressing. So far I used HiFiGAN V1. VITS version performs better for unseen speaker than LJSpeech. However better than both HiFiGANs - at the moment - is BigVGAN. Still way to go to be even close to VITS2 (1m),

<img width="687" alt="image" src="https://github.com/p0p4k/pflowtts_pytorch/assets/6952336/ffe5496d-f3e9-4ae1-9c44-f820cdec17e7">

Regarding DiffWave... it is posible to eliminate mel spectogram "proxy" completely like https://arxiv.org/pdf/2311.00945.pdf

**Comment by p0p4k** [comment]
Can you add me on discord? (id: p0p4k)
